//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests.Data.Assess.Dashboard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfileHomeResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfileHomeResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Data.Assess.Dashboard.ProfileHomeResource", typeof(ProfileHomeResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 12.
        /// </summary>
        internal static string GradeLevelHigh_valid_v17 {
            get {
                return ResourceManager.GetString("GradeLevelHigh.valid.v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 1.
        /// </summary>
        internal static string GradeLevelLow_valid_v17 {
            get {
                return ResourceManager.GetString("GradeLevelLow.valid.v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Test.
        /// </summary>
        internal static string RecentlyViewedTests_valid_v17 {
            get {
                return ResourceManager.GetString("RecentlyViewedTests.valid.v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language and Literature.
        /// </summary>
        internal static string Subject_valid_v17 {
            get {
                return ResourceManager.GetString("Subject.valid.v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12345.
        /// </summary>
        internal static string TestId_valid_v17 {
            get {
                return ResourceManager.GetString("TestId.valid.v17", resourceCulture);
            }
        }
    }
}
