//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests.Data.Assess.Schedule {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditAssignmentCourseResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditAssignmentCourseResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Data.Assess.Schedule.EditAssignmentCourseResource", typeof(EditAssignmentCourseResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AddSelected_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("AddSelected_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AddSelected_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("AddSelected_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AssignedCourseName_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("AssignedCourseName_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AssignedCourseName_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("AssignedCourseName_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTING 1.
        /// </summary>
        internal static string AvailableCourseName_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("AvailableCourseName_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACTING 1.
        /// </summary>
        internal static string AvailableCourseName_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("AvailableCourseName_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Course_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Course_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Course_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Course_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29-2010-229100.
        /// </summary>
        internal static string CourseId_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("CourseId_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 29-2010-229100.
        /// </summary>
        internal static string CourseId_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("CourseId_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Department_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Department_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Department_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Department_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 12.
        /// </summary>
        internal static string GradeHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 12.
        /// </summary>
        internal static string GradeHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        internal static string GradeLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        internal static string GradeLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LimitBySchools_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("LimitBySchools_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LimitBySchools_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("LimitBySchools_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RemoveSelected_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("RemoveSelected_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RemoveSelected_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("RemoveSelected_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string ResultsPerPage_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ResultsPerPage_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 500.
        /// </summary>
        internal static string ResultsPerPage_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ResultsPerPage_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RowNumber_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("RowNumber_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string RowNumber_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("RowNumber_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
    }
}
