//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests.Data.Login {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AuthenticationResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AuthenticationResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Data.Login.AuthenticationResource", typeof(AuthenticationResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_districtadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_districtadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_districtadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_districtadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to junk.
        /// </summary>
        internal static string DistrictName_invalid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_invalid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to junk.
        /// </summary>
        internal static string DistrictName_invalid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_invalid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_leadership_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_leadership_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_leadership_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_leadership_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DistrictName_null_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_null_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DistrictName_null_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_null_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_regionaladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_regionaladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_regionaladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_regionaladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_schooladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_schooladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_schooladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_schooladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York State.
        /// </summary>
        internal static string DistrictName_stateadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_stateadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schoolnet Account.
        /// </summary>
        internal static string DistrictName_stateadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_stateadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York State.
        /// </summary>
        internal static string DistrictName_statesuperadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_statesuperadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schoolnet Account.
        /// </summary>
        internal static string DistrictName_statesuperadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_statesuperadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York State.
        /// </summary>
        internal static string DistrictName_student_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_student_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schoolnet Account.
        /// </summary>
        internal static string DistrictName_student_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_student_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_systemsetup_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_systemsetup_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_systemsetup_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_systemsetup_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York State.
        /// </summary>
        internal static string DistrictName_systemsetupstate_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_systemsetupstate_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schoolnet Account.
        /// </summary>
        internal static string DistrictName_systemsetupstate_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_systemsetupstate_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_teacher_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_teacher_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_teacher_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_teacher_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_valid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_valid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string DistrictName_valid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DistrictName_valid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harkless.
        /// </summary>
        internal static string FirstName_student_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("FirstName_student_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harkless.
        /// </summary>
        internal static string FirstName_student_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("FirstName_student_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andreani.
        /// </summary>
        internal static string LastName_student_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("LastName_student_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Andreani.
        /// </summary>
        internal static string LastName_student_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("LastName_student_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Passcode_student_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Passcode_student_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Passcode_student_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Passcode_student_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_districtadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_districtadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_districtadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_districtadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to junk.
        /// </summary>
        internal static string Password_invalid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_invalid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to junk.
        /// </summary>
        internal static string Password_invalid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_invalid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_leadership_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_leadership_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_leadership_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_leadership_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Password_null_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_null_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Password_null_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_null_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_regionaladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_regionaladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_regionaladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_regionaladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_schooladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_schooladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_schooladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_schooladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_stateadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_stateadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_stateadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_stateadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_statesuperadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_statesuperadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_statesuperadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_statesuperadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_student_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_student_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_student_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_student_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_systemsetup_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_systemsetup_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_systemsetup_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_systemsetup_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_systemsetupstate_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_systemsetupstate_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_systemsetupstate_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_systemsetupstate_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_teacher_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_teacher_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_teacher_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_teacher_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_valid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Password_valid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sch00lnet.
        /// </summary>
        internal static string Password_valid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Password_valid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_districtadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_districtadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_districtadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_districtadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username and password combination..
        /// </summary>
        internal static string PasswordErrorMessage_invalid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_invalid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username and password combination..
        /// </summary>
        internal static string PasswordErrorMessage_invalid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_invalid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_leadership_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_leadership_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_leadership_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_leadership_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_null_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_null_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_null_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_null_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_regionaladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_regionaladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_regionaladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_regionaladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_schooladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_schooladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_schooladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_schooladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_stateadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_stateadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_stateadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_stateadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_statesuperadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_statesuperadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_statesuperadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_statesuperadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_student_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_student_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_student_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_student_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_systemsetup_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_systemsetup_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_systemsetup_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_systemsetup_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_systemsetupstate_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_systemsetupstate_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_systemsetupstate_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_systemsetupstate_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_teacher_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_teacher_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_teacher_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_teacher_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_valid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_valid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PasswordErrorMessage_valid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PasswordErrorMessage_valid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to admin.
        /// </summary>
        internal static string Username_districtadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_districtadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn_qa.
        /// </summary>
        internal static string Username_districtadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_districtadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to junk.
        /// </summary>
        internal static string Username_invalid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_invalid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to junk.
        /// </summary>
        internal static string Username_invalid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_invalid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bm_leadership.
        /// </summary>
        internal static string Username_leadership_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_leadership_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bm_leadership.
        /// </summary>
        internal static string Username_leadership_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_leadership_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Username_null_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_null_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Username_null_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_null_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north_admin.
        /// </summary>
        internal static string Username_regionaladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_regionaladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north_admin.
        /// </summary>
        internal static string Username_regionaladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_regionaladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bm_schooladmin.
        /// </summary>
        internal static string Username_schooladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_schooladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bm_schooladmin.
        /// </summary>
        internal static string Username_schooladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_schooladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to state_assess.
        /// </summary>
        internal static string Username_stateadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_stateadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn_qa.
        /// </summary>
        internal static string Username_stateadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_stateadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn_qa.
        /// </summary>
        internal static string Username_statesuperadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_statesuperadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn_qa.
        /// </summary>
        internal static string Username_statesuperadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_statesuperadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1222889.
        /// </summary>
        internal static string Username_student_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_student_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1057500.
        /// </summary>
        internal static string Username_student_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_student_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sys_setup.
        /// </summary>
        internal static string Username_systemsetup_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_systemsetup_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sys_setup.
        /// </summary>
        internal static string Username_systemsetup_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_systemsetup_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sys_setup.
        /// </summary>
        internal static string Username_systemsetupstate_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_systemsetupstate_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sys_setup.
        /// </summary>
        internal static string Username_systemsetupstate_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_systemsetupstate_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dware5.
        /// </summary>
        internal static string Username_teacher_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_teacher_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dware5.
        /// </summary>
        internal static string Username_teacher_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_teacher_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn_qa.
        /// </summary>
        internal static string Username_valid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Username_valid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn_qa.
        /// </summary>
        internal static string Username_valid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Username_valid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_districtadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_districtadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_districtadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_districtadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username and password combination..
        /// </summary>
        internal static string UsernameErrorMessage_invalid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_invalid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect username and password combination..
        /// </summary>
        internal static string UsernameErrorMessage_invalid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_invalid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_leadership_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_leadership_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_leadership_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_leadership_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_null_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_null_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_null_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_null_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_regionaladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_regionaladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_regionaladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_regionaladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_schooladmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_schooladmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_schooladmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_schooladmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_stateadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_stateadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_stateadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_stateadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_statesuperadmin_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_statesuperadmin_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_statesuperadmin_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_statesuperadmin_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_student_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_student_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_student_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_student_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_systemsetup_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_systemsetup_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_systemsetup_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_systemsetup_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_systemsetupstate_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_systemsetupstate_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_systemsetupstate_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_systemsetupstate_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_teacher_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_teacher_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_teacher_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_teacher_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_valid_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_valid_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string UsernameErrorMessage_valid_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UsernameErrorMessage_valid_schoolnetsingletenant_v17", resourceCulture);
            }
        }
    }
}
