//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests.Data.Assess.ItemCreateEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemStatisticsResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemStatisticsResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Data.Assess.ItemCreateEdit.ItemStatisticsResource", typeof(ItemStatisticsResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BloomsTaxonomy_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("BloomsTaxonomy_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string BloomsTaxonomy_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("BloomsTaxonomy_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ItemMeanHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ItemMeanHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ItemMeanHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ItemMeanHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ItemMeanLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ItemMeanLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ItemMeanLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ItemMeanLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string ItemTotalScoreHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ItemTotalScoreHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string ItemTotalScoreHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ItemTotalScoreHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string ItemTotalScoreLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ItemTotalScoreLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string ItemTotalScoreLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ItemTotalScoreLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ItemType_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ItemType_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ItemType_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ItemType_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PassageType_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PassageType_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PassageType_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PassageType_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string PValueHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PValueHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string PValueHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PValueHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string PValueLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PValueLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string PValueLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PValueLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionLanguage_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("QuestionLanguage_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionLanguage_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("QuestionLanguage_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string RaschItemDifficultyHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("RaschItemDifficultyHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string RaschItemDifficultyHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("RaschItemDifficultyHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string RaschItemDifficultyLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("RaschItemDifficultyLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.0.
        /// </summary>
        internal static string RaschItemDifficultyLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("RaschItemDifficultyLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ResponseTimeHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ResponseTimeHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ResponseTimeHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ResponseTimeHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ResponseTimeLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ResponseTimeLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ResponseTimeLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ResponseTimeLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Spoken_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Spoken_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Spoken_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Spoken_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Written_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Written_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Written_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Written_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
    }
}
