//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests.Data.Assess.ItemCreateEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TrueFalseItemResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TrueFalseItemResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Data.Assess.ItemCreateEdit.TrueFalseItemResource", typeof(TrueFalseItemResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnswerChoiceLayoutOption_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("AnswerChoiceLayoutOption_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string AnswerChoiceLayoutOption_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("AnswerChoiceLayoutOption_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;True&quot;, &quot;False&quot;.
        /// </summary>
        internal static string AnswerList_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("AnswerList_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;True&quot;, &quot;False&quot;.
        /// </summary>
        internal static string AnswerList_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("AnswerList_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;True&quot;.
        /// </summary>
        internal static string CorrectAnswerList_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("CorrectAnswerList_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;True&quot;.
        /// </summary>
        internal static string CorrectAnswerList_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("CorrectAnswerList_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CorrectAnswerPair_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("CorrectAnswerPair_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CorrectAnswerPair_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("CorrectAnswerPair_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Exemplars_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Exemplars_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Exemplars_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Exemplars_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FilePath_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("FilePath_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string FilePath_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("FilePath_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 12.
        /// </summary>
        internal static string GradeHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 12.
        /// </summary>
        internal static string GradeHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        internal static string GradeLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        internal static string GradeLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ItemID_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ItemID_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string ItemID_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ItemID_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrueFalse.
        /// </summary>
        internal static string ItemType_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ItemType_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TrueFalse.
        /// </summary>
        internal static string ItemType_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ItemType_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumberOfAnswerSheetPages_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("NumberOfAnswerSheetPages_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NumberOfAnswerSheetPages_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("NumberOfAnswerSheetPages_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PassageTitle_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PassageTitle_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PassageTitle_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PassageTitle_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PointValueList_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PointValueList_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string PointValueList_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PointValueList_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;True&quot;, &quot;5&quot;.
        /// </summary>
        internal static string PointValuePair_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PointValuePair_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;True&quot;, &quot;5&quot;.
        /// </summary>
        internal static string PointValuePair_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PointValuePair_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionAnswerPair_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("QuestionAnswerPair_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionAnswerPair_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("QuestionAnswerPair_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the fruits and vegetables to their colors.
        /// </summary>
        internal static string QuestionContent_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("QuestionContent_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match the fruits and vegetables to their colors.
        /// </summary>
        internal static string QuestionContent_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("QuestionContent_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionEndingAfterLastGap_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("QuestionEndingAfterLastGap_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionEndingAfterLastGap_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("QuestionEndingAfterLastGap_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionList_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("QuestionList_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string QuestionList_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("QuestionList_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ResponseType_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ResponseType_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ResponseType_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ResponseType_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ScoringInstructions_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ScoringInstructions_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ScoringInstructions_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ScoringInstructions_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string StudentAnswer_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("StudentAnswer_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string StudentAnswer_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("StudentAnswer_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StudentAnswerList_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("StudentAnswerList_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StudentAnswerList_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("StudentAnswerList_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StudentAnswerPair_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("StudentAnswerPair_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StudentAnswerPair_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("StudentAnswerPair_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;student&apos;s explanation&quot;.
        /// </summary>
        internal static string StudentExplanationList_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("StudentExplanationList_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;student&apos;s explanation&quot;.
        /// </summary>
        internal static string StudentExplanationList_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("StudentExplanationList_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StudentInstructions_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("StudentInstructions_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string StudentInstructions_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("StudentInstructions_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;teacher&apos;s explanation&quot;.
        /// </summary>
        internal static string TeacherExplanationList_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("TeacherExplanationList_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;teacher&apos;s explanation&quot;.
        /// </summary>
        internal static string TeacherExplanationList_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("TeacherExplanationList_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string TestTunnelIndex_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("TestTunnelIndex_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string TestTunnelIndex_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("TestTunnelIndex_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
    }
}
