//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests.Data.Assess.Standards {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SelectedStandardsGroupResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SelectedStandardsGroupResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Data.Assess.Standards.SelectedStandardsGroupResource", typeof(SelectedStandardsGroupResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Class_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Class_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Class_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Class_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string StandardDocumentId_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("StandardDocumentId_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 35.
        /// </summary>
        internal static string StandardDocumentId_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("StandardDocumentId_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7945.
        /// </summary>
        internal static string StandardId_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("StandardId_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7945.
        /// </summary>
        internal static string StandardId_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("StandardId_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LA.2.W.1.A.
        /// </summary>
        internal static string StandardName_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("StandardName_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LA.2.W.1.A.
        /// </summary>
        internal static string StandardName_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("StandardName_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language and Literature.
        /// </summary>
        internal static string Subject_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Subject_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language and Literature.
        /// </summary>
        internal static string Subject_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Subject_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
    }
}
