//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests.Data.Assess.Rubric {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RubricResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RubricResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Data.Assess.Rubric.RubricResource", typeof(RubricResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col.
        /// </summary>
        internal static string ColumnLabel_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ColumnLabel_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to col.
        /// </summary>
        internal static string ColumnLabel_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ColumnLabel_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string Description_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Description_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to description.
        /// </summary>
        internal static string Description_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Description_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 3.
        /// </summary>
        internal static string GradeHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 3.
        /// </summary>
        internal static string GradeHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 2.
        /// </summary>
        internal static string GradeLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 2.
        /// </summary>
        internal static string GradeLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group label.
        /// </summary>
        internal static string GroupLabel_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GroupLabel_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group label.
        /// </summary>
        internal static string GroupLabel_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GroupLabel_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RubricKeyword.
        /// </summary>
        internal static string Keyword_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Keyword_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RubricKeyword.
        /// </summary>
        internal static string Keyword_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Keyword_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Test Rubric: .
        /// </summary>
        internal static string Name_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Name_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Test Rubric: .
        /// </summary>
        internal static string Name_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Name_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string Publisher_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Publisher_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string Publisher_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Publisher_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string QuestionLanguage_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("QuestionLanguage_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string QuestionLanguage_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("QuestionLanguage_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row.
        /// </summary>
        internal static string RowLabel_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("RowLabel_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to row.
        /// </summary>
        internal static string RowLabel_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("RowLabel_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Scale_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Scale_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string Scale_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Scale_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language and Literature.
        /// </summary>
        internal static string Subject_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Subject_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language and Literature.
        /// </summary>
        internal static string Subject_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Subject_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
    }
}
