//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests.Data.Assess.Passage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PassageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PassageResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Data.Assess.Passage.PassageResource", typeof(PassageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 111.
        /// </summary>
        internal static string AdditionalPassageID_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("AdditionalPassageID_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 111.
        /// </summary>
        internal static string AdditionalPassageID_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("AdditionalPassageID_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher instructions.
        /// </summary>
        internal static string AddTeacherInstructions_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("AddTeacherInstructions_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher instructions.
        /// </summary>
        internal static string AddTeacherInstructions_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("AddTeacherInstructions_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 222.
        /// </summary>
        internal static string AssetType_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("AssetType_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 222.
        /// </summary>
        internal static string AssetType_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("AssetType_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 233.
        /// </summary>
        internal static string Author_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Author_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 233.
        /// </summary>
        internal static string Author_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Author_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 555.
        /// </summary>
        internal static string Batch_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Batch_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 555.
        /// </summary>
        internal static string Batch_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Batch_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string BeginningReader_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("BeginningReader_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string BeginningReader_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("BeginningReader_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 333.
        /// </summary>
        internal static string CourseID_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("CourseID_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 333.
        /// </summary>
        internal static string CourseID_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("CourseID_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolNet.
        /// </summary>
        internal static string CreatedBy_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("CreatedBy_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolNet.
        /// </summary>
        internal static string CreatedBy_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("CreatedBy_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.0.
        /// </summary>
        internal static string FleschKincaid_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("FleschKincaid_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.0.
        /// </summary>
        internal static string FleschKincaid_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("FleschKincaid_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 444.
        /// </summary>
        internal static string Genre_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Genre_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABC 444.
        /// </summary>
        internal static string Genre_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Genre_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 12.
        /// </summary>
        internal static string GradeHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 12.
        /// </summary>
        internal static string GradeHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        internal static string GradeLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        internal static string GradeLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HideOptionalProperties_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("HideOptionalProperties_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HideOptionalProperties_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("HideOptionalProperties_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        internal static string Lexile_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Lexile_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 80.
        /// </summary>
        internal static string Lexile_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Lexile_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LexileCode_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("LexileCode_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LexileCode_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("LexileCode_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string NumberOfWordsFrom_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("NumberOfWordsFrom_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string NumberOfWordsFrom_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("NumberOfWordsFrom_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NumberOfWordsTo_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("NumberOfWordsTo_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NumberOfWordsTo_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("NumberOfWordsTo_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FIFA World Cup (also called the Football World Cup, the Soccer World Cup, or simply the World Cup) is an international association football competition contested by the senior men&apos;s national teams of the members of Federation International de Football Association (FIFA), the sport&apos;s global governing body. The championship has been awarded every four years since the inaugural tournament in 1930, except in 1942 and 1946 when it was not held because of the Second World War. The current champions are Spain, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PassageText_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PassageText_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FIFA World Cup (also called the Football World Cup, the Soccer World Cup, or simply the World Cup) is an international association football competition contested by the senior men&apos;s national teams of the members of Federation International de Football Association (FIFA), the sport&apos;s global governing body. The championship has been awarded every four years since the inaugural tournament in 1930, except in 1942 and 1946 when it was not held because of the Second World War. The current champions are Spain, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PassageText_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PassageText_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolNet.
        /// </summary>
        internal static string Publisher_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Publisher_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SchoolNet.
        /// </summary>
        internal static string Publisher_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Publisher_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string QuestionLanguage_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("QuestionLanguage_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string QuestionLanguage_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("QuestionLanguage_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.51.
        /// </summary>
        internal static string ReadingMaturityMetric_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ReadingMaturityMetric_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.51.
        /// </summary>
        internal static string ReadingMaturityMetric_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ReadingMaturityMetric_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language and Literature.
        /// </summary>
        internal static string Subject_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Subject_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language and Literature.
        /// </summary>
        internal static string Subject_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Subject_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Test Passage: .
        /// </summary>
        internal static string Title_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Title_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Test Passage: .
        /// </summary>
        internal static string Title_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Title_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Cup.
        /// </summary>
        internal static string Topic_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Topic_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to World Cup.
        /// </summary>
        internal static string Topic_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Topic_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poetry.
        /// </summary>
        internal static string Type_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Type_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poetry.
        /// </summary>
        internal static string Type_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Type_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2010.
        /// </summary>
        internal static string Year_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Year_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2010.
        /// </summary>
        internal static string Year_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Year_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
    }
}
