//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UITests.Data.Assess.TestCreateEdit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CreateTestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateTestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UITests.Data.Assess.TestCreateEdit.CreateTestResource", typeof(CreateTestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string CentimeterRuler_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("CentimeterRuler_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string CentimeterRuler_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("CentimeterRuler_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Compass_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Compass_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Compass_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Compass_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a test.
        /// </summary>
        internal static string Description_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Description_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to create a test.
        /// </summary>
        internal static string Description_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Description_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DisableTextFormattingOpenResponse_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("DisableTextFormattingOpenResponse_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DisableTextFormattingOpenResponse_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("DisableTextFormattingOpenResponse_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string EnableEquationEditor_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("EnableEquationEditor_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string EnableEquationEditor_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("EnableEquationEditor_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableNo_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("EnableNo_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableNo_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("EnableNo_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableTextFormattingOpenResponse_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("EnableTextFormattingOpenResponse_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableTextFormattingOpenResponse_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("EnableTextFormattingOpenResponse_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableYes_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("EnableYes_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string EnableYes_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("EnableYes_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 12.
        /// </summary>
        internal static string GradeHigh_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gr 12.
        /// </summary>
        internal static string GradeHigh_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeHigh_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        internal static string GradeLow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindergarten.
        /// </summary>
        internal static string GradeLow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("GradeLow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string InchRuler_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("InchRuler_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string InchRuler_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("InchRuler_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string InstitutionSource_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("InstitutionSource_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National School District.
        /// </summary>
        internal static string InstitutionSource_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("InstitutionSource_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LinkToTestWindow_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("LinkToTestWindow_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string LinkToTestWindow_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("LinkToTestWindow_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NumberOfItems_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("NumberOfItems_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string NumberOfItems_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("NumberOfItems_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohio English Language Arts 2003.
        /// </summary>
        internal static string PreferredStandardsDocument_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("PreferredStandardsDocument_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ohio English Language Arts 2003.
        /// </summary>
        internal static string PreferredStandardsDocument_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("PreferredStandardsDocument_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Protractor_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Protractor_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string Protractor_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Protractor_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score.
        /// </summary>
        internal static string ScoreType_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("ScoreType_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Score.
        /// </summary>
        internal static string ScoreType_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("ScoreType_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string StudentCommentEndOfTest_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("StudentCommentEndOfTest_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string StudentCommentEndOfTest_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("StudentCommentEndOfTest_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language and Literature.
        /// </summary>
        internal static string Subject_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("Subject_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Language and Literature.
        /// </summary>
        internal static string Subject_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("Subject_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Benchmark.
        /// </summary>
        internal static string TestCategory_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("TestCategory_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District Benchmark.
        /// </summary>
        internal static string TestCategory_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("TestCategory_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation Test.
        /// </summary>
        internal static string TestId_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("TestId_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automation Test.
        /// </summary>
        internal static string TestId_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("TestId_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string UnitRuler_default_schoolnetmultitenant_v17 {
            get {
                return ResourceManager.GetString("UnitRuler_default_schoolnetmultitenant_v17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string UnitRuler_default_schoolnetsingletenant_v17 {
            get {
                return ResourceManager.GetString("UnitRuler_default_schoolnetsingletenant_v17", resourceCulture);
            }
        }
    }
}
